namespace CarbonCore.Unity.Utils.Logic.Enums
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Linq;

    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<AnchorPoint> AnchorPointValues = Enum.GetValues(typeof(AnchorPoint)).Cast<AnchorPoint>().ToList();

        public static readonly IList<BehaviorTreeCompositeMode> BehaviorTreeCompositeModeValues = Enum.GetValues(typeof(BehaviorTreeCompositeMode)).Cast<BehaviorTreeCompositeMode>().ToList();

        public static readonly IList<BehaviorTreeDecoratorMode> BehaviorTreeDecoratorModeValues = Enum.GetValues(typeof(BehaviorTreeDecoratorMode)).Cast<BehaviorTreeDecoratorMode>().ToList();

        public static readonly IList<BehaviorTreeStatus> BehaviorTreeStatusValues = Enum.GetValues(typeof(BehaviorTreeStatus)).Cast<BehaviorTreeStatus>().ToList();

        public static readonly IList<BundleLoadFlags> BundleLoadFlagsValues = Enum.GetValues(typeof(BundleLoadFlags)).Cast<BundleLoadFlags>().ToList();

        public static readonly IList<DelayedLoadedObjectPhase> DelayedLoadedObjectPhaseValues = Enum.GetValues(typeof(DelayedLoadedObjectPhase)).Cast<DelayedLoadedObjectPhase>().ToList();

        public static readonly IList<Orientation> OrientationValues = Enum.GetValues(typeof(Orientation)).Cast<Orientation>().ToList();

        public static readonly IList<ResourceLoadFlags> ResourceLoadFlagsValues = Enum.GetValues(typeof(ResourceLoadFlags)).Cast<ResourceLoadFlags>().ToList();

        public static readonly IList<ResourceLoadMode> ResourceLoadModeValues = Enum.GetValues(typeof(ResourceLoadMode)).Cast<ResourceLoadMode>().ToList();

        public static readonly IList<SceneTransitionStep> SceneTransitionStepValues = Enum.GetValues(typeof(SceneTransitionStep)).Cast<SceneTransitionStep>().ToList();

        public static readonly IList<SqlDbType> SqlDbTypeValues = Enum.GetValues(typeof(SqlDbType)).Cast<SqlDbType>().ToList();

    }
}