namespace CarbonCore.ContentServices.Logic.Enums
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IList<CompressionLevel> CompressionLevelValues = Enum.GetValues(typeof(CompressionLevel)).Cast<CompressionLevel>().ToList();

        public static readonly IList<TiledMapLayerType> TiledMapLayerTypeValues = Enum.GetValues(typeof(TiledMapLayerType)).Cast<TiledMapLayerType>().ToList();

        public static readonly IList<TiledMapOrientation> TiledMapOrientationValues = Enum.GetValues(typeof(TiledMapOrientation)).Cast<TiledMapOrientation>().ToList();

        public static readonly IList<TiledMapRenderOrder> TiledMapRenderOrderValues = Enum.GetValues(typeof(TiledMapRenderOrder)).Cast<TiledMapRenderOrder>().ToList();

    }
}