namespace CarbonCore.CrystalBuild.Enums
{
    using System.Collections.Generic;
    
    using CarbonCore.Utils;
	
    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IReadOnlyCollection<BuildTargetType> BuildTargetTypeValues = EnumExtensions.GetValues<BuildTargetType>();

    }
}